title: Site title
description: > # this means to ignore newlines until "baseurl:"
  Site description
permalink: ':title/'
baseurl: "/jekyll-simple-blog-template" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Olga Strijewski # add your name
author-img: olga.jpg # add your photo
about-author: I am a Senior Solution Architect / Lead Developer with over 20 years of in-depth, hands-on experience designing, building and leading teams to create mission-critical software systems.
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: olsido # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Site Settings
site-name: Site Name
site-logo-img: visual-studio-code-logo.svg
about-site: Site description

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
